### ISSUE TITLE
regression: file picker loses context when switching to edit view

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#738]
In the file picker popup (when using ``FilerFileField`` or ``FilerImageField`` in admin) allows navigating to the "edit" view of items and allows creating folders. But after such actions the "context" that we're actually in file picker mode gets lost.

- [x] looses context when saving a file (#761)
- [x] looses context when deleting a file (#761)
- [x] looses context when deleting a folder (#772)
- [x] looses context when creating a new folder (#772)
- [x] popup closes when editing/saving a Folder (Django 1.9) (#772)
- [x] popup closes when editing/saving a File (Django 1.9) (#772)
- [x] ~~``raw_id_field`` to ``File`` /  ``Folder`` /  ``Image`` does not close popup on save~~ wontfix for now

**Comment by stefanfoulis** [comment]
This is still an issue in Django 1.9 (possibly Django 1.7+). re-opening.
